-- players
INSERT INTO PLAYER (NAME) VALUES ('Federer');
INSERT INTO PLAYER (NAME) VALUES ('Nadal');
INSERT INTO PLAYER (NAME) VALUES ('Djokovic');
INSERT INTO PLAYER (NAME) VALUES ('Murray');
INSERT INTO PLAYER (NAME) VALUES ('Safin');
INSERT INTO PLAYER (NAME) VALUES ('Williams');
INSERT INTO PLAYER (NAME) VALUES ('Sharapova');
INSERT INTO PLAYER (NAME) VALUES ('Thiem');
INSERT INTO PLAYER (NAME) VALUES ('Halep');
INSERT INTO PLAYER (NAME) VALUES ('Medvedev');


-- matches
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 2, 1);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (3, 4, 3);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (5, 6, 5);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (7, 8, 8);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (9, 10, 9);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (2, 5, 2);
INSERT INTO MATCH (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (4, 7, 4);
